# This workflow is largely based on
# https://github.com/salsify/ember-css-modules/blob/master/.github/workflows/ci.yml

name: CI

# These trigger patterns courtesy of https://github.com/broccolijs/broccoli/pull/436
on:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - 'v*'
    # always run CI for tags
    tags:
      - '*'

  # early issue detection: run CI weekly on Sundays
  schedule:
    - cron: '0 6 * * 0'

env:
  CI: true

jobs:
  test-floating-deps:
    name: Floating Deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@bcad811784fb09d282bb1a9a98dfc18f758fbd9e
        with:
          version: 6.14.5
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test:ember

  test-old-dependencies:
    name: Oldest Supported Env
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@bcad811784fb09d282bb1a9a98dfc18f758fbd9e
        with:
          version: 6.14.5
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: pnpm
      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm test:ember

  test-try:
    runs-on: ubuntu-20.04
    needs: [test-floating-deps]

    strategy:
      fail-fast: false
      matrix:
        scenario:
          - ember-lts-3.12
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          #- ember-lts-3.28
          - ember-release
          - ember-beta
          - ember-canary
          - ember-default-with-jquery
          - ember-classic
          - embroider-safe
          - embroider-optimized

    name: 'ember-try: ${{ matrix.scenario }}'

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@bcad811784fb09d282bb1a9a98dfc18f758fbd9e
        with:
          version: 6.14.5
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm ember try:one ${{ matrix.scenario }}
